title:            Sietse Ringers
description:      Personal website of Sietse Ringers
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://www.sietseringers.net
disqus_shortname:

# Owner/author information
owner:
  name:           Sietse Ringers
  avatar:         bio-photo.jpg
  # bio:            "Describe your self."
  email:          mail@sietseringers.net
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:
  facebook:
  github:
  stackoverflow:
  linkedin:
  instagram:
  lastfm:
  tumblr:
  pinterest:
  foursquare:
  steam:
  dribbble:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:


# Links to include in top navigation
# For external links add external: true
links:
  - title: Contact
    url: "#contact"
  - title: Github profile
    url: https://github.com/sietseringers
    external: true
  - title: IRMA project
    url: https://www.irmacard.org
    external: true
  - title: PEP project
    url: http://pep.cs.ru.nl
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Amsterdam
future:      true
markdown:    kramdown
highlighter: rouge

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
